/**
 * Run api-extractor against the monorepo
 */

import { runExtractorForMonorepo, runExtractorForPackage } from "./monorepo-api-extractor";

const silent = process.argv.includes('--silent');
const dryRun = process.argv.includes('--dry-run');

const pkgOnly = process.argv.includes('--package-only');
const ignoreErrors
  = process.argv.includes('--ignore-errors') || process.env.TSDOCS_IGNORE_ERRORS;
/**
 * The option to control if reports are generated by api-extractor
 */
const apiReportEnabled = process.argv.includes('--report');

async function main() {
  if (pkgOnly) {
    runExtractorForPackage(process.cwd(), { silent, dryRun, ignoreErrors });
    return;
  }
  await runExtractorForMonorepo({
    silent,
    dryRun,
    ignoreErrors,
    apiReportEnabled,
  });
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
